# Generated by Django 4.1.4 on 2022-12-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_handler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageblock",
            name="image",
            field=models.ImageField(upload_to="image_block/user_uploads/"),
        ),
    ]
