# Generated by Django 4.1.4 on 2022-12-08 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("image_handler", "0003_imageblock_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageblock",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="imageblock",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
